training_list:
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/131_P23-629/Data/ortho/131P23629_Orthomosaic_export_MonOct30224934156397.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/131_P23-629/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/131_P23-629/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/160_P22-404/Data/ortho/160P22404_Orthomosaic_export_SunOct15042957495542.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/160_P22-404/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/160_P22-404/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/161_P22-405/Data/ortho/161P22405_Orthomosaic_export_SatOct14192426314827.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/161_P22-405/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/161_P22-405/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/162_P22-406/Data/ortho/162P22406_Orthomosaic_export_SunOct15043125960263.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/162_P22-406/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/162_P22-406/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/168_P22-207/Data/ortho/168_ortho.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/168_P22-207/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/168_P22-207/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/170_P22-408/Data/ortho/170_ortho.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/170_P22-408/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/170_P22-408/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/171_P22-529/Data/ortho/171_ortho.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/171_P22-529/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/171_P22-529/Training/AOI_2.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/179_P22-732/Data/ortho/179_ortho.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/179_P22-732/Training/Buffered_Trees_1.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/179_P22-732/Training/AOI_1.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/177_P22-639/Data/ortho/177_ortho.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/177_P22-639/Training/Buffered_Trees_1.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/177_P22-639/Training/AOI_1.geojson'
]
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/180_P22-739/Data/ortho/180_ortho.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/180_P22-739/Training/Buffered_Trees_1.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/180_P22-739/Training/AOI_1.geojson'
]
validation_list:
- ['/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/160_P22-404/Data/ortho/160P22404_Orthomosaic_export_SunOct15042957495542.tif',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/160_P22-404/Training/Buffered_Trees_2.geojson',
'/home/aerotract/NAS/main/Clients/10041_WeyerhaeuserSpringfield/101037_Fall2023SurvivalSurveys/160_P22-404/Training/AOI_2.geojson'
]
# output path for training/evaluation results
output_root_uri: '/home/aerotract/NAS/main/ml_storage/PreTrainedModels/SpringfieldFall23'

# Class config for this experiment, defines class names and colors
class_config:
  names: ["DF"]
  colors: ["red"]

# Chip options for creating chips from dataset images
chip_options:
  neg_ratio: 0.0
  ioa_thresh: 0.75 #0.8

# Window options for creating tiled datasets from images
window_config:
  chip_sz: 800 #1000
  img_sz: 800 #1000
  max_windows: 500

# Model backbone options - different model sources need different parameters
backbone_config:  
  source: "rastervision"
  name: "resnet152"  #resnet152, resnext101_32x8d
# backbone_config:
#   source: "external"
#   github_repo: "AdeelH/vision:det_hubconf_0.12"
#   name: "ssd"
#   entrypoint: "ssd300_vgg16"
#   force_reload: True
#   pretrained: False
#   pretrained_backbone: True

# Hyperparams and params for solver used in training
solver_config:
  lr: 5e-6
  num_epochs: 9
  batch_sz: 4  #8
  one_cycle: True
  test_num_epochs: 1

# Hyperparams for prediction bounding boxes
predict_options:
  merge_thresh: 0.1
  score_thresh: 0.10

# Number of workers to deploy on the system
num_workers: 8

# Tensorboard controls
tensorboard:
  log: True
  run: True

# Environment variables to set before running pipeline
env:
  apply: False
  QT_QPA_PLATFORM: "offscreen"
  CUDA_VISIBLE_DEVICES: "-1"