training_list:
  - ['/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-402-P1/P22-402-P1_05172022/Data/ortho/WCSF10505172022P1.tif',
    '/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-402-P1/P22-402-P1_05172022/Modeling/P22-402_results_spring22/P22-402_model.shp'
  ]
  - ['/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-403-P1/P22-403-P1_05172022/Data/ortho/WCSF10605172022P1.tif',
    '/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-403-P1/P22-403-P1_05172022/Modeling/P22-403_model/P22-403_model.shp'
  ]
  - ['/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-407-P1/P22-407-P1_04112022/Data/ortho/WCSF10104112022P1.tif',
    '/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-407-P1/P22-407-P1_04112022/Modeling/WCSF10104112022P1_BAM5/WCSF10104112022P1.shp'
  ]
  - ['/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-408-P1/P22-408-P1_04062022/Data/ortho/WCSF09704062022P1.tif',
    '/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-408-P1/P22-408-P1_04062022/Modeling/clean_t.60.shp'
  ]
# [image, labels, boundary] file groups for evaluation
validation_list:
  - ['/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-629-P1/P22-629-P1_05162022/Data/ortho/WCSF10805162022P1.tif',
    '/home/aerotract/NAS/main/Clients/Weyerhauser/Springfield_Spring2022/P22-629-P1/P22-629-P1_05162022/Modeling/P22-629_model/P22-629_model.shp'
  ]

# output path for training/evaluation results
output_root_uri: 's3://rvml-results/test2'

# Class config for this experiment, defines class names and colors
class_config:
  names: ["DF"]
  colors: ["red"]

# Chip options for creating chips from dataset images
chip_options:
  neg_ratio: 0.1
  ioa_thresh: 0.8

# Window options for creating tiled datasets from images
window_config:
  chip_sz: 450
  img_sz: 450
  max_windows: 450

# Model backbone options - different model sources need different parameters
# backbone_config:  
#   source: "rastervision"
#   name: "resnet18"
backbone_config:
  source: "external"
  github_repo: "AdeelH/vision:det_hubconf_0.12"
  name: "ssd"
  entrypoint: "ssd300_vgg16"
  force_reload: True
  pretrained: False
  pretrained_backbone: True

# Hyperparams and params for solver used in training
solver_config:
  lr: 1e-4
  num_epochs: 1
  batch_sz: 8
  one_cycle: True
  test_num_epochs: 1

# Hyperparams for prediction bounding boxes
predict_options:
  merge_thresh: 0.1
  score_thresh: 0.8

# Number of workers to deploy on the system
num_workers: 16

# Tensorboard controls
tensorboard:
  log: True
  run: True

# Environment variables to set before running pipeline
env:
  apply: True
  QT_QPA_PLATFORM: "offscreen"
  CUDA_VISIBLE_DEVICES: "-1"