
# training_list:
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/103_WardsButteSx/Data/ortho/03WardsButteSxGR02122023_Orthomosaic_WedMar08194203915827/03WardsButteSxGR02122023_Orthomosaic_export_WedMar08194203915827.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/103_WardsButteSx/Training/WardsButte_trees_poly.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/103_WardsButteSx/Training/WardsButte_sample_boundary.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/104_FinalSalem/Data/ortho/04FinalSalemGR02122023_Orthomosaic_WedMar08195655345878/04FinalSalemGR02122023_Orthomosaic_export_WedMar08195655345878.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/104_FinalSalem/Training/FinalSalem_tree_polys.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/104_FinalSalem/Training/finalSalem_sample_Boundary.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Data/ortho/05WinstormGR02122023_Orthomosaic_WedMar08201410773708/05WinstormGR02122023_Orthomosaic_export_WedMar08201410773708.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Training/Tree_poly.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Training/Sample_Boundary.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/108_Moffit/Data/ortho/08MoffitGR02122023_Orthomosaic_export_FriMar10183649417525.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/108_Moffit/Training/Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/108_Moffit/Training/Boundary.geojson' 
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Training/Tree_polygons_00_230OG.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Training/Trees2.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Training/Boundry2.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Data/ortho/Wiley520Junction_Orthomosaic_FriApr07171157298390/Wiley520Junction_Orthomosaic_export_FriApr07171157298390.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Training/tree_points.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Training/Boundary.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/101_RC480/101_RC480_North/Data/ortho/Map1_Orthomosaic_export_FriMar24032400677478.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/101_RC480/101_RC480_North/Training/Buffered_Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/101_RC480/101_RC480_North/Training/Boundry.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/101_RC480/101_RC480_Middle/Data/ortho/Map1_Orthomosaic_export_FriMar24034656140787.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/101_RC480/101_RC480_Middle/Training/Buffered_Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/101_RC480/101_RC480_Middle/Training/Boundry.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/102_RockyRidge/Data/ortho/02RockyRidgeGR02122023_Orthomosaic_WedMar08191856469683/02RockyRidgeGR02122023_Orthomosaic_export_WedMar08191856469683.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/102_RockyRidge/Training/Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/102_RockyRidge/Training/Boundry.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/102_RockyRidge/Data/ortho/02RockyRidgeGR02122023_Orthomosaic_WedMar08191856469683/02RockyRidgeGR02122023_Orthomosaic_export_WedMar08191856469683.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/102_RockyRidge/Training/DF minus fluffly trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/102_RockyRidge/Training/DF minus fluffly trees boundry.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/106_Winfire/Data/ortho/06WinfireGR02122023_Orthomosaic_WedMar08213557063397/06WinfireGR02122023_Orthomosaic_export_WedMar08213557063397.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/106_Winfire/Training/Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/106_Winfire/Training/Boundry.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/104_FinalSalem/Data/ortho/04FinalSalemGR02122023_Orthomosaic_WedMar08195655345878/04FinalSalemGR02122023_Orthomosaic_export_WedMar08195655345878.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/104_FinalSalem/Training/BufferedTrees_Shade.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/104_FinalSalem/Training/Boundary_Shade.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/106_Winfire/Data/ortho/06WinfireGR02122023_Orthomosaic_WedMar08213557063397/06WinfireGR02122023_Orthomosaic_export_WedMar08213557063397.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/106_Winfire/Training/Shade_Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/106_Winfire/Training/Shade_Boundary.geojson'
#   ]
#   - [
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/115_MealyFinaly/115_MealyFinalyWest/Data/ortho/115MealyFinalyWest_Orthomosaic_export_FriMar24042915460821.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/115_MealyFinaly/115_MealyFinalyWest/Training/Trees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/115_MealyFinaly/115_MealyFinalyWest/Training/Boundry.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Data/ortho/Wiley520Junction_Orthomosaic_FriApr07171157298390/Wiley520Junction_Orthomosaic_export_FriApr07171157298390.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Training/SnowTrees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Training/SnowyBoundry.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Data/ortho/05WinstormGR02122023_Orthomosaic_WedMar08201410773708/05WinstormGR02122023_Orthomosaic_export_WedMar08201410773708.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Training/ToughTrees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Training/ToughBoundary.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_00_GM640E_P1/CTCI_00_GM640E_P1_01192023/Data/ortho/00GM640E01192023_Orthomosaic_TueMar07184733321630/00GM640E01192023_Orthomosaic_export_TueMar07184733321630.tif',
#     '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_00_GM640E_P1/CTCI_00_GM640E_P1_01192023/Training/Buffered_Trees.geojson',
#     '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_00_GM640E_P1/CTCI_00_GM640E_P1_01192023/Training/Boundry.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Data/ortho/05WinstormGR02122023_Orthomosaic_WedMar08201410773708/05WinstormGR02122023_Orthomosaic_export_WedMar08201410773708.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Training/ShadeTrees.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/105_WinStormGTF/Training/ShadeBoundary.geojson'
#   ]
#   # - ['/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_02_CedarStrip_P1/CTCI_02_CedarStrip_P1_01052023/Data/ortho/02CedarStrip01052023_Orthomosaic_TueMar07011727419652/02CedarStrip01052023_Orthomosaic_export_TueMar07011727419652.tif',
#   #   '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_02_CedarStrip_P1/CTCI_02_CedarStrip_P1_01052023/Training/Buffered_Trees.geojson',
#   #   '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_02_CedarStrip_P1/CTCI_02_CedarStrip_P1_01052023/Training/Boundries.geojson'
#   # ]

# validation_list:
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Data/ortho/230OG_Orthomosaic_export_WedMar08181810258552.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Training/Tree_polygons_00_230OG.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/100_230OG/Training/border_polygon_00_230OG.geojson'
#   ]
#   - ['/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Data/ortho/Wiley520Junction_Orthomosaic_FriApr07171157298390/Wiley520Junction_Orthomosaic_export_FriApr07171157298390.tif',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Training/tree_points.geojson',
#   '/home/aerotract/NAS/Clients/Giustina/Winter2023/112_Wiley520Junction/Training/Boundary.geojson'
#   ]


#### Sunnyside  ########
# training_list:
#   - ['/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_12_SunnysideUp/CTCI_12_SunnysideUp_01302023/Data/ortho/112SunnysideUpReflight_Orthomosaic_TueApr11230834955486/112SunnysideUpReflight_Orthomosaic_export_TueApr11230834955486.tif',
#   '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_12_SunnysideUp/CTCI_12_SunnysideUp_01302023/Training/Trees.geojson',
#   '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_12_SunnysideUp/CTCI_12_SunnysideUp_01302023/Training/Boundry.geojson'
#   ]

# validation_list:
#   - ['/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_12_SunnysideUp/CTCI_12_SunnysideUp_01302023/Data/ortho/112SunnysideUpReflight_Orthomosaic_TueApr11230834955486/112SunnysideUpReflight_Orthomosaic_export_TueApr11230834955486.tif',
#   '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_12_SunnysideUp/CTCI_12_SunnysideUp_01302023/Training/Trees.geojson',
#   '/home/aerotract/NAS/Clients/Cascade/CTCI_Winter2023/CTCI_12_SunnysideUp/CTCI_12_SunnysideUp_01302023/Training/Boundry.geojson'
#   ]




####  PINE #####
training_list:
  - ['/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/100_25899297/Data/ortho/100_25899297_EPSG4326_Max/10025899297_Orthomosaic_export_TueMar28173552656224.tif',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/100_25899297/Training/Buffered_Trees.geojson',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/100_25899297/Training/boundaries.geojson'
  ]
  - ['/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/101_25921184/Data/ortho/101_25921184_EPSG4326_Max/10125921184_Orthomosaic_export_TueMar28181956822473.tif',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/101_25921184/Training/Buffered_Trees.geojson',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/101_25921184/Training/boundaries.geojson'
  ]
  - ['/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/103_25901341/Data/ortho/103_25901341_EPSG4326_Max/10325901341_Orthomosaic_export_TueMar28182920265925.tif',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/103_25901341/Training/Buffered_Trees.geojson',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/103_25901341/Training/bounaries.geojson'
  ]
  - ['/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/104_34015502/Data/ortho/104_34015502_Max_Available_EPSG_4326/104_34015502_Max_Available_EPSG_4326.tif',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/104_34015502/Training/Buffered_Trees.geojson',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/104_34015502/Training/boundaries.geojson'
  ]
  - ['/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/105_25885365/Data/ortho/105_258855365_Max_Available_EPSG_4326/105258855365_Orthomosaic_export_TueMar28184531308012.tif',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/105_25885365/Training/Buffered_Trees.geojson',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/105_25885365/Training/boundaries.geojson'
  ]
  - ['/home/aerotract/NAS/Clients/Manulife/Fall-2022/MANL_02_335935_P1/MANL_335935_02_P1_12172022/Data/ortho/335935_Orthomosaic_export_TueMar28203555114537.tif',
  '/home/aerotract/NAS/Clients/Manulife/Fall-2022/MANL_02_335935_P1/MANL_335935_02_P1_12172022/Training/tree_sample_02.geojson',
  '/home/aerotract/NAS/Clients/Manulife/Fall-2022/MANL_02_335935_P1/MANL_335935_02_P1_12172022/Training/sample_boundary_02.geojson'
  ]


validation_list:
  - ['/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/100_25899297/Data/ortho/100_25899297_EPSG4326_Max/10025899297_Orthomosaic_export_TueMar28173552656224.tif',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/100_25899297/Training/Buffered_Trees.geojson',
  '/home/aerotract/NAS/Clients/WeyerhaeuserLA/WeycoSurvivalInventory2023/100_25899297/Training/boundaries.geojson'
  ]





# training_list:
#   - ['/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-102-P1/P22-102-P1_04052022/Data/ortho/WCSF102.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-102-P1/P22-102-P1_04052022/Training/Trees.geojson'
#   ]

# validation_list:
#   - ['/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-102-P1/P22-102-P1_04052022/Data/ortho/WCSF102.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-102-P1/P22-102-P1_04052022/Training/Trees.geojson'
#   ]


# training_list:
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF08903282022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-749-P1/P22-749-P1_03282022/Training/Tree.geojson'
#   ]
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF08803242022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-748-P1/P22-748-P1_03242022/Training/Tree.geojson'
#   ]
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF08703242022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-746-P1/P22-746-P1_03242022/Training/Tree.geojson'
#   ]
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF09403312022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-659-P1/P22-659-P1_03312022/Training/Tree.geojson'
#   ]
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF11105172022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-651-P1/P22-651-P1_05172022/Training/Trees.geojson'
#   ]
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF11605232022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-637-P1/P22-637_P1_05232022/Training/Tree.geojson'
#   ]

# validation_list:
#   - ['/home/aerotract/GoBag/Migrate/dev/DataBase/FirstYearDF/WCSF09403312022P14326.tif',
#   '/home/aerotract/NAS/Clients/Weyerhauser/Springfield_Spring2022/P22-659-P1/P22-659-P1_03312022/Training/Tree.geojson'
#   ]


# output path for training/evaluation results
output_root_uri: '/home/aerotract/GoBag/Migrate/dev/PreTrainedModels/PineModels/FirstYearPine/Resnet50'

# Class config for this experiment, defines class names and colors
class_config:
  names: ["DF"]
  colors: ["red"]

# Chip options for creating chips from dataset images
chip_options:
  neg_ratio: .1
  ioa_thresh: 0.7 #50 percent for big trees, 75 percent for seedlings

# Window options for creating tiled datasets from images
window_config:
  chip_sz: 800
  img_sz: 800
  max_windows: 1500

# Model backbone options - different model sources need different parameters
backbone_config:  
  source: "rastervision"
  name: "resnet50"
# backbone_config:
#   source: "external"
#   github_repo: "AdeelH/vision:det_hubconf_0.12"
#   name: "ssd"
#   entrypoint: "ssd300_vgg16"
#   force_reload: True
#   pretrained: False
#   pretrained_backbone: True

# Hyperparams and params for solver used in training
solver_config:
  lr: 1e-4
  num_epochs: 12
  batch_sz: 16
  one_cycle: True
  test_num_epochs: 1

# Hyperparams for prediction bounding boxes
predict_options:
  merge_thresh: 0.1
  score_thresh: 0.70

# Number of workers to deploy on the system
num_workers: 8

# Tensorboard controls
tensorboard:
  log: True
  run: True

# Environment variables to set before running pipeline
env:
  apply: False
  QT_QPA_PLATFORM: "offscreen"
  CUDA_VISIBLE_DEVICES: "-1"
