training_list:
- ['/home/aerotract/NAS/main/Clients/10007_Chinook/101031_Chinook_WA_Chelan_2023/100_SpinMove/Data/ortho/100_ortho.tif',
'/home/aerotract/NAS/main/Clients/10007_Chinook/101031_Chinook_WA_Chelan_2023/100_SpinMove/Training/points_0.geojson',
'/home/aerotract/NAS/main/Clients/10007_Chinook/101031_Chinook_WA_Chelan_2023/100_SpinMove/Training/AOI_0.geojson'
]

validation_list:
- ['/home/aerotract/NAS/main/Clients/10007_Chinook/101031_Chinook_WA_Chelan_2023/103_ItsGoTime/Data/ortho/103_ortho.tif',
'/home/aerotract/NAS/main/Clients/10007_Chinook/101031_Chinook_WA_Chelan_2023/103_ItsGoTime/Validation/points_0.geojson',
'/home/aerotract/NAS/main/Clients/10007_Chinook/101031_Chinook_WA_Chelan_2023/103_ItsGoTime/Validation/AOI_0.geojson'
]


# output path for training/evaluation results
output_root_uri: ''

# Class config for this experiment, defines class names and colors
class_config:
  names: ["DF"]
  colors: ["red"]

# Chip options for creating chips from dataset images
chip_options:
  # neg_ratio: 0.0
  ioa_thresh: 0.75 #0.8

# Window options for creating tiled datasets from images
window_config:
  chip_sz: 500 #1000
  img_sz: 500 #1000
  max_windows: 500

# Model backbone options - different model sources need different parameters
backbone_config:  
  source: "rastervision"
  name: "resnet152"  #resnet152, resnext101_32x8d
# backbone_config:
#   source: "external"
#   github_repo: "AdeelH/vision:det_hubconf_0.12"
#   name: "ssd"
#   entrypoint: "ssd300_vgg16"
#   force_reload: True
#   pretrained: False
#   pretrained_backbone: True

# Hyperparams and params for solver used in training
solver_config:
  lr: 5e-6
  num_epochs: 9
  batch_sz: 8  #8
  one_cycle: True
  test_num_epochs: 1

# Hyperparams for prediction bounding boxes
predict_options:
  merge_thresh: 0.1
  score_thresh: 0.10

# Number of workers to deploy on the system
num_workers: 8

# Tensorboard controls
tensorboard:
  log: True
  run: True

# Environment variables to set before running pipeline
env:
  apply: False
  QT_QPA_PLATFORM: "offscreen"
  CUDA_VISIBLE_DEVICES: "-1"